perf-test-daemon: retry email a few times
Because:

Traceback (most recent call last):
  File /home/douglasb/samba-cloud-autobuild/perf-daemon/perf-test-daemon, line 404, in <module>
    main()
  File /home/douglasb/samba-cloud-autobuild/perf-daemon/perf-test-daemon, line 394, in main
    process_queue()
  File /home/douglasb/samba-cloud-autobuild/perf-daemon/perf-test-daemon, line 291, in process_queue
    send_email(subject, body, results)
  File /home/douglasb/samba-cloud-autobuild/perf-daemon/perf-test-daemon, line 147, in send_email
    s.sendmail(recipient, [recipient], str(msg))
  File /usr/lib/python2.7/smtplib.py, line 751, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (451, '4.7.1 Try again later')